# Generated by Django 2.1.2 on 2018-10-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encouraged', models.BooleanField()),
                ('activity', models.CharField(max_length=256)),
                ('purpose', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=256)),
                ('diagnosis_description', models.CharField(max_length=2048)),
                ('activity_warnings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Actions')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encouraged', models.BooleanField()),
                ('activity', models.CharField(max_length=256)),
                ('purpose', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encouraged', models.BooleanField()),
                ('activity', models.CharField(max_length=256)),
                ('purpose', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('primary_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
                ('dosage', models.CharField(max_length=256)),
                ('cycle', models.CharField(max_length=256)),
                ('purpose', models.CharField(max_length=2048)),
                ('activity_warnings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Actions')),
                ('diet_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Diet')),
                ('environment_warnings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Treatment')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diet_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Diet'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='environment_warnings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Environment'),
        ),
    ]
