# Generated by Django 2.1.2 on 2018-10-06 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181006_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='activity_warnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Actions'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diet_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Diet'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='environment_warnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Environment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Doctor'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='activity_warnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Actions'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diet_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Diet'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dosage',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='environment_warnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Environment'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Treatment'),
        ),
    ]
