# Generated by Django 2.1.2 on 2018-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181006_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'ordering': ['activity']},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['diagnosis_name']},
        ),
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ['activity']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['activity']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['prescription']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='twilio_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='activity_warnings',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='activity_warnings',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Actions'),
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diet_change',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diet_change',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Diet'),
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='environment_warnings',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='environment_warnings',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Environment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='activity_warnings',
        ),
        migrations.AddField(
            model_name='treatment',
            name='activity_warnings',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Actions'),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='diet_change',
        ),
        migrations.AddField(
            model_name='treatment',
            name='diet_change',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Diet'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='environment_warnings',
        ),
        migrations.AddField(
            model_name='treatment',
            name='environment_warnings',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Environment'),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.ManyToManyField(to='backend.Diagnosis'),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='treatment',
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Treatment'),
        ),
    ]
