# Generated by Django 2.1.2 on 2018-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181006_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.CharField(default='07833d18-464f-4bba-8f07-adbbb2c3f917', max_length=50, primary_key=True, serialize=False),
        ),
    ]
